### ISSUE TITLE
Hacker News Headlines Emailer issue

### ISSUE THREAD

**Issue by tsamlama** [amrrs/build_tools_to_automate_python#1]
on the first project : I should get all the 30 article but i got only 1 , i thought there is a problem in my loop but i did same as the video but didn't work ...
`for i, tag in enumerate(soup.find_all('td', attrs={'class':'title','valign':''})):`
 

`cnt += ((str(i+1)+' :: '+tag.text + "\n" + '<br>') if tag.text!='More' else '')`

`return(cnt)`

this is what my email looks like:

HN Top Stories:
--------------------------------------------------
1 :: Show HN: I made a web game called Almost Pong ([lessmilk.com](http://lessmilk.com/))

------

End of Message

**Comment by amrrs** [comment]
Hey Thanks for raising the issue here. Can you share the entire code that you used to try? just the scraping part

**Comment by tsamlama** [comment]
> Hey Thanks for raising the issue here. Can you share the entire code that you used to try? just the scraping part

`def extract_news(url):`
     `print('Extracting Hacker news Stories...')`
`cnt='' `
`cnt +=('<b>HN Top Stories:</b>\n'+'<br>'+'-'*50+'<br>')`
`response = requests.get(url) `
`content = response.content `
`soup = BeautifulSoup(content, 'html.parser') `
`for i, tag in enumerate(soup.find_all('td', attrs={'class':'title','valign':''})):`
`cnt += ((str(i+1)+' :: '+tag.text + "\n" + '<br>') if tag.text!='More' else '')`
`return (cnt)`

`cnt = extract_news('https://news.ycombinator.com/')`
`content += cnt`
`content += ('<br>------</br>') `
`content += ('<br><br>End of Message')`

**Comment by MITCHCONNOR886** [comment]
The code works fine for me

**Comment by ODubDubH3** [comment]
You need to indent line 9, cnt+=((str(i+1)..., otherwise the loop ends after the first iteration.

**Comment by amrrs** [comment]
Thanks @ODubDubH3 for the comment. Appreciate it. I seemed to have missed this!

**Comment by ODubDubH3** [comment]
Thanks to you for putting the videos out there!


Wendell Holmes

406-447-8319

**Comment by amrrs** [comment]
Thank you @ODubDubH3 I'm trying to post more Automation videos - https://www.youtube.com/playlist?list=PLpdmBGJ6ELUIDexUW-_hgz1JA86aAT7eZ 

Check it out when you get time, Always up for feedback and improvements!
