### ISSUE TITLE
Issue with the ted talk downloader

### ISSUE THREAD

**Issue by CoryOConnor94** [amrrs/build_tools_to_automate_python#2]
Hi I'm having issues with the ted talk downloader code. Can't find the script tag name you used in the video ether so I'm not sure if the website is no longer allowing downloads or if the issue is with the code. Appreciate your Python course on Youtube its great , Thanks.

**Comment by amrrs** [comment]
Hey Thanks for sharing your feedback and raising this issue. I appreciate it. I'll check it out. Do you have any more feedback for my course?

**Comment by amrrs** [comment]
@MITCHCONNOR886 I got a new tutorial for ted talk downloader - https://www.youtube.com/watch?v=kxulmN9-bRM

**Comment by CoryOConnor94** [comment]
Thanks, I just finished it great work as always.

**Comment by amrrs** [comment]
Thank you
