### ISSUE TITLE
Less secure app access is no longer available

### ISSUE THREAD

**Issue by bharath-13** [amrrs/build_tools_to_automate_python#4]
To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.

![Screenshot (509)](https://user-images.githubusercontent.com/36135810/171631463-e0fb7184-5c7e-42e2-9004-03c60ed89bc4.png)

**Comment by amrrs** [comment]
Thanks for bringing it to my attention @bharath-13 I didn't know this
